services:
  nginx:
    build: ./app1
    ports: 
      - 80:9090

    depends_on:
      - app2
      - app3
    networks:
        - app-net
  app2:
    build: .
    networks:
      - app-net
  app3:
    build: .
    networks:
      - app-net
  
networks:
  app-net:
    driver: bridge
    
