services:
  app1:
    build: ./app1
    ports:
      - "8080:80"
    depends_on:
      - app2_0
      - app2_1
      - app2_2
      - app3_0
      - app3_1
      - app3_2

  app2_0:
    build: .
    volumes:
      - ./app2:/usr/share/nginx/html
  app2_1:
    build: .
    volumes:
      - ./app2:/usr/share/nginx/html
  app2_2:
    build: .
    volumes:
      - ./app2:/usr/share/nginx/html      
  app3_0:
    build: .
    volumes:
      - ./app3:/usr/share/nginx/html
  app3_1:
    build: .
    volumes:
      - ./app3:/usr/share/nginx/html      
  app3_2:
    build: .
    volumes:
      - ./app3:/usr/share/nginx/html      