events {}

http {
  resolver 172.20.0.10 ipv6=off valid=5s;

  server {
    listen 80;
    

    location / {
      add_header Cache-Control "no-store, no-cache, must-revalidate";
      add_header Pragma "no-cache";

      default_type text/html;

      return 200 '
        <h1>app1</h1>
        <a href="/app2/">Ir para App2</a><br>
        <a href="/app3/">Ir para App3</a>
      ';
    }

    location /app2/ {
      proxy_pass http://aplicativo2.dns/;
    }

    location /app3/ {
      proxy_pass http://aplicativo3.dns/;
    }
  }
}