events{}

http {
  upstream app2 {
    server app2_0:80;
    server app2_1:80;
    server app2_2:80;
  }
  upstream app3 {
    server app3_0:80;
    server app3_1:80;
    server app3_2:80;
  }

  server {
    listen 80;
    server_name  localhost;

    location / {
      default_type text/html;
      return 200 '
        <h1>app1</h1>
        <a href="/app2/">Ir para App2</a><br>
        <a href="/app3/">Ir para App3</a>
      ';
    }

    location /app2/ {
      proxy_pass http://app2/;
      proxy_set_header Host $host; 
    }

    location /app3/ {
      proxy_pass http://app3/;
      proxy_set_header Host $host; 
    }
  }
}