events{}

http {
  
  resolver 127.0.0.11 valid=5s;
  server {
    listen 80;
    server_name  localhost;

    location / {
      default_type text/html;
      return 200 '
        <h1>app1</h1>
        <a href="/app2/">Ir para App2</a><br>
        <a href="/app3/">Ir para App3</a>
      ';
      
    }

    location /app2/ {
      set $backend "http://aplicativo2.local";

      proxy_pass $backend;

      proxy_set_header Host $host;
      
    }

    location /app3/ {
      set $backend "http://aplicativo3.local";

      proxy_pass $backend;

      proxy_set_header Host $host;
      
    }
  }
}